name: flutter_soaring_forecast
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.10.0+34

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:

  async: ^2.9.0
  # upgrading dio/retrofit would give:
  #  DioError [DioErrorType.DEFAULT]: type 'String' is not a subtype of type 'Map<String, dynamic>'
  dio: ^4.0.6
  dio_logging_interceptor: ^1.0.1
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  retrofit: '>=3.0.0 <4.0.0'
  logger: ^1.1.0  #for logging purpose
  provider: ^6.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.5
  pinch_zoom: ^1.0.0
  sprintf: ^6.0.0
  cupertino_back_gesture: ^0.1.0
  cupertino_will_pop_scope: ^1.2.1
  path_provider: ^2.0.14      # for access to image cache manager and downloads directory
  permission_handler: ^10.2.0  # for permissions to downloads directory, location
  location: ^4.4.0 # Get location via GPS - also provides permission so overlap with above
  flutter_svg: ^1.1.3   #Used to draw turnpoint icons
  linked_scroll_controller: 0.2.0   # Used for grid view with fixed header and column
  device_info_plus: ^8.2.2  # Get platform-specific device info. In this case used to get Android version

  flutter_cache_manager: ^3.3.0
  intl: ^0.17.0   # used for date/time formatting
  after_layout: ^1.2.0
  floor: ^1.3.0
  # https://pub.dev/packages/csv/install
  csv: ^5.0.1
  path: ^1.8.1
  sqflite: ^2.0.3+1
  shared_preferences: ^2.0.15
  scrollable_positioned_list: ^0.3.2
  flutter_html: ^3.0.0-alpha.3
  email_launcher: ^1.1.1
  package_info_plus: ^1.0.6  # for getting version name and build number
  email_validator: '^2.1.16'
  syncfusion_flutter_pdfviewer:
    path: ../syncfusion_flutter_pdfviewer-21.2.3
  graphic: ^1.0.0

  mockito: ^5.3.0   # needed for Android dev - not sure why
  http: ^0.13.5
  workmanager: ^0.5.0   #0.5.0-dev.8   # to help download airports file (used for METAR/TAF)
  flutter_launcher_icons: ^0.10.0

  flutter_map: ^3.0.0 # or the latest version on Pub, current used for rasp map
  #map_controller: 0.9.1  # used to process/display SUA plus handle state with showing/removing markers
  google_maps_flutter: ^2.2.0 # used for overhead view of turnpoints
  geojson_vector_slicer:
    path: ../geojson_vector_slicer

  flutter:
    sdk: flutter
 # map_controller:       # library not developed enough for what I need
 #   path: ../map_controller

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  firebase_core: ^2.7.1
  firebase_crashlytics: ^3.0.16


#https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: 'assets/png/glider_app_icon.png'
  min_sdk_android: 20


dev_dependencies:

  flutter_driver:
    sdk: flutter

  test: ^1.21.1

  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: '>=2.2.1 <4.0.0'
  floor_generator: ^1.3.0

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/json/
    - assets/svg/
    - assets/png/
    - assets/html/
    - assets/txt/
    - assets/csv/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
