name: flutter_soaring_forecast
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.0+50

environment:
  sdk: ">=3.4.3 <=3.6.2"

dependencies:

  async: ^2.11.0
  # upgrading dio/retrofit would give:
  #  DioError [DioErrorType.DEFAULT]: type 'String' is not a subtype of type 'Map<String, dynamic>'
  dio: ^5.2.1
  json_serializable: ^6.9.3
  json_annotation: ^4.8.1
  retrofit: '^4.0.3'
  logger: ^2.3.0  #for logging purpose
  provider: ^6.0.3
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1
  # pinch_zoom: ^2.0.0 # ^1.0.0
  sprintf: ^7.0.0
  cupertino_back_gesture: ^0.1.0
  cupertino_will_pop_scope: ^1.2.1
  path_provider: ^2.0.14      # for access to image cache manager and downloads directory
  permission_handler: ^11.3.1  # for permissions to downloads directory, location
  location: ^7.0.1 # Get location via GPS - also provides permission so overlap with above
  flutter_svg:  ^2.0.17  #  ^1.1.3   #Used to draw turnpoint icons
  linked_scroll_controller: 0.2.0   # Used for grid view with fixed header and column
  device_info_plus: ^11.0.0  # Get platform-specific device info. In this case used to get Android version
  vector_math: ^2.1.4    # methods used for thermalling sink rate calculations

  flutter_cache_manager: ^3.3.0
  intl: ^0.19.0   # used for date/time formatting,  syncfusion_flutter_pdfviewer 28.2.4 depends on intl >=0.18.1 <0.20.0
  after_layout: ^1.2.0
  floor: ^1.5.0
  # https://pub.dev/packages/csv/install
  csv: ^6.0.0
  path: ^1.9.0  # can't upgrade to 1.9.1 as conflicts with flutter_test
  sqflite: ^2.0.3+1
  shared_preferences: ^2.3.2
  scrollable_positioned_list: ^0.3.2
  flutter_html: ^3.0.0-alpha.3

  package_info_plus: 8.2.0 #^4.0.2  # for getting version name and build number
  email_validator: '^3.0.0'
  syncfusion_flutter_pdfviewer: ^28.2.4
  #  path: ../syncfusion_flutter_pdfviewer-21.2.3
  graphic:  2.5.1
  colorize: any    # used by dio interceptor

  mockito: ^5.3.0   # needed for Android dev - not sure why
  http: ^1.2.1
  workmanager: ^0.5.2   #0.5.0-dev.8   # to help download airports file (used for METAR/TAF)
  flutter_launcher_icons: ^0.14.3

  flutter_map:  ^7.0.2 # can't upgrade until get update to or replace flutter_map_geojson
  flutter_map_animations: ^0.7.0  # see flutter_map above
  google_maps_flutter: ^2.2.0 # used for overhead view of turnpoints
  flutter_map_geojson: ^1.0.8  # replaced geojson_vector_slicer
  #geojson_vector_slicer:
  #  path: ../geojson_vector_slicer

  flutter:
    sdk: flutter
 # map_controller:       # library not developed enough for what I need
 #   path: ../map_controller

  cupertino_icons: ^1.0.5
  firebase_core: ^3.11.0
  firebase_crashlytics: ^4.3.2


#https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: 'assets/png/glider_app_icon.png'
  min_sdk_android: 20


dev_dependencies:

  flutter_driver:
    sdk: flutter

  test: ^1.21.1

  retrofit_generator: '9.1.7'
  build_runner: '>=2.2.1 <4.0.0'


  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata.ttf

  assets:
    - assets/json/
    - assets/svg/
    - assets/png/
    - assets/html/
    - assets/txt/
    - assets/csv/
    - assets/ca/
    - assets/fonts/


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
