// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK7LN7f-5xTc4jitkrAftuVmELo1vJxU8',
    appId: '1:390759997758:android:1e16ab864d345c83590c6f',
    messagingSenderId: '390759997758',
    projectId: 'soaringforecast-48021',
    storageBucket: 'soaringforecast-48021.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3fqNiWI1HAn0oRAWDEXZRv91Z7kMbBzs',
    appId: '1:390759997758:ios:1c494acdbb444f8a590c6f',
    messagingSenderId: '390759997758',
    projectId: 'soaringforecast-48021',
    storageBucket: 'soaringforecast-48021.appspot.com',
    androidClientId: '390759997758-87bqhk1tg992373g8qtov48b7jjjgitu.apps.googleusercontent.com',
    iosClientId: '390759997758-0ambrp4rtbeob08is8i8kk5uf3h3hp13.apps.googleusercontent.com',
    iosBundleId: 'org.soaringforecast.rasp',
  );
}
